Ot196 59 create migration
alkemyTech/OT196-Server pull request #19
Opened 2022-06-01 17:26 UTC by PedroBraude

https://alkemy-labs.atlassian.net/browse/OT196-59

**Features**

- Add model, migration and seeder.

**Evidence**
![image](https://user-images.githubusercontent.com/32098492/171465815-880ee805-0157-4ba4-b841-8e6abd94c44a.png)

2022-06-03 01:44 UTC, GauntStrelok requested changes

2022-06-03 01:44 UTC, GauntStrelok commented on migrations/20220601170216-create-activity.js
> +      image: {
image esta dos veces

2022-06-03 01:44 UTC, GauntStrelok commented on models/activity.js
> +    image: DataTypes.STRING,
image esta dos veces x2

2022-06-03 01:44 UTC, GauntStrelok commented
Una pavada, chequea de arreglar eso :)

2022-06-03 12:36 UTC, PedroBraude commented on migrations/20220601170216-create-activity.js
> +      image: {
Que pavo, ya lo corrijo.

2022-06-03 12:36 UTC, PedroBraude commented on models/activity.js
> +    image: DataTypes.STRING,
oka.

2022-06-06 11:24 UTC, GauntStrelok commented
No veo el arreglo en el PR

2022-06-06 15:07 UTC, merged